### ISSUE TITLE
Not receiving response from CURL.XPOST calls

### ISSUE THREAD

**Issue by todd-lockhart** [jdarwood007/sql-curl#1]
When calling CURL.XPOST, the procedure seems to be executing properly, but no response is returned. I am only presented with the confirmation that the coded executed (i.e., standard 'OK, Time: x.xxxxxs' response).

**Comment by jdarwood007** [comment]
How are you handling receiving the data?

This is a fork of the one from Microsoft: https://github.com/microsoft/sql-server-samples
I implanted PUT as needed by the API I am communicating with.  I didn't need PATCH, but its really easy to add as well.

Other than that, I simply use a procedure as a wrapper:
```
CREATE PROCEDURE [dbo].[curlPost]
	@URI			nvarchar(max)	= NULL,
	@AuthorizationToken	varchar(200)	= NULL,
	@BodyData		nvarchar(max)	= NULL
AS
SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
BEGIN
	DECLARE
		@headers	varchar(500)	= 'Content-Type: application/json;Authorization:',
		@responseJSON	nvarchar(MAX)	= '';
	SET @headers = @headers + @AuthorizationToken;

	SET @responseJSON = CURL.XPOST(@headers, @BodyData, @URI);
	SELECT @responseJSON;
	RETURN;
END
```

Then my main calling procedure can call this sub procedure with the url, auth token and data I am sending.

```
DECLARE @json AS TABLE(Json_Table text);
INSERT INTO @json (Json_Table) 
EXEC [dbo].[curlPost](@URI, @AuthorizationToken, @BodyData)
```

I receive a string with json data back, which I then format into readable data, which is a simple select from OPENJSON..

**Comment by todd-lockhart** [comment]
My fault. I used structure exactly from sample code in README without using my brain :/

The structure there is -
exec curl.XPOST @H = @hkey, @d = @body, @url = @endpoint;

Using the structure as written in the SQL source and as you list above (i.e., with parameters in parentheses) works just fine.

Thanks for today's dose of humility :)
